apiVersion: apps/v1
kind: Deployment
metadata:
  name: payload
  labels:
    app: payload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payload
  template:
    metadata:
      labels:
        app: payload
    spec:
      containers:
        - name: payload
          image: johnnyy06/payload:v1.0
          ports:
            - containerPort: 80
          env:
            # Environment variables for your frontend apps
            - name: VUE_CHAT_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: payload-config
                  key: VUE_CHAT_FRONTEND_URL
            - name: VUE_AI_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: payload-config
                  key: VUE_AI_FRONTEND_URL
            
            # Payload v3 specific environment variables
            - name: PAYLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  name: payload-secrets
                  key: payload-secret
            - name: DATABASE_URI
              value: "file:/app/.payload/payload.db"
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_SERVER_URL
              value: "http://localhost:80"
          # Health checks
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5