apiVersion: apps/v1
kind: Deployment
metadata:
  name: payload
  labels:
    app: payload
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payload
  template:
    metadata:
      labels:
        app: payload
    spec:
      containers:
        - name: payload
          image: johnnyy06/payload:latest
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "mkdir -p /var/www/html/tmp/regularlabs/custom_php && chown -R www-data:www-data /var/www/html/tmp && chmod -R 755 /var/www/html/tmp",
                  ]
          env:
            - name: VUE_CHAT_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: payload-config
                  key: VUE_CHAT_FRONTEND_URL

            - name: VUE_AI_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: payload-config
                  key: VUE_AI_FRONTEND_URL

            - name: PAYLOAD_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_DATABASE_HOST

            - name: PAYLOAD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_PASSWORD

            - name: PAYLOAD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_USER

            - name: PAYLOAD_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_DATABASE

            - name: PAYLOAD_DB_TYPE
              value: "mysqli"