apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend-deployment
  labels:
    app: chatapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: johnnyy06/chatapp-frontend:v1.3
        ports:
        - containerPort: 90
        livenessProbe:
          httpGet:
            path: /health
            port: 90
          initialDelaySeconds: 30
          periodSeconds: 10