# OCR Backend Service
apiVersion: v1
kind: Service
metadata:
  name: ocr-backend-service
spec:
  selector:
    app: ocr-backend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort