# Simple Site Service
apiVersion: v1
kind: Service
metadata:
  name: simple-site-service
spec:
  selector:
    app: simple-site
  ports:
    - name: http
      protocol: TCP
      port: 80  # Site-ul principal pe portul 80
      targetPort: 80
  type: NodePort