apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS chatdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    USE chatdb;

    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL,
        message TEXT NOT NULL,
        timestamp DATETIME NOT NULL,
        INDEX idx_timestamp (timestamp)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    INSERT INTO messages (username, message, timestamp)
    VALUES 
        ('System', 'Bine ati venit in aplicatia de chat!', NOW() - INTERVAL 5 MINUTE),
        ('Admin', 'Aplicatia foloseste WebSocket pentru comunicare in timp real.', NOW() - INTERVAL 4 MINUTE);

    CREATE USER IF NOT EXISTS 'chatuser'@'%' IDENTIFIED BY 'parola123';
    GRANT ALL PRIVILEGES ON chatdb.* TO 'chatuser'@'%';
    FLUSH PRIVILEGES;
