apiVersion: v1
kind: Service
metadata:
  name: ocr-backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ocr-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http