apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-frontend-deployment
  labels:
    app: ocr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-frontend
  template:
    metadata:
      labels:
        app: ocr-frontend
    spec:
      containers:
      - name: ocr-frontend
        image: johnnyy06/ocr-frontend:v1.5
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10