# ChatApp Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend-deployment
spec:
  replicas: 1  # Conform cerințelor: 1 replică
  selector:
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: johnnyy06/chatapp-frontend:latest
        ports:
        - containerPort: 90