# OCR Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-backend
  template:
    metadata:
      labels:
        app: ocr-backend
    spec:
      containers:
      - name: ocr-backend
        image: johnnyy06/ocr-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: FRONTEND_URL
          value: "http://ocr-frontend-service:80"
        # Adaugă aici variabilele pentru Azure când le ai
        # - name: AZURE_STORAGE_CONNECTION_STRING
        #   value: "your-connection-string"
        # - name: OCR_ENDPOINT
        #   value: "your-ocr-endpoint"
        # - name: OCR_KEY
        #   value: "your-ocr-key"