# Simple Site Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-site
  template:
    metadata:
      labels:
        app: simple-site
    spec:
      containers:
      - name: simple-site
        image: johnnyy06/simple-site:latest
        ports:
        - containerPort: 80